import type { Page } from "@playwright/test";

export type ScenarioSnapshot = Record<string, string>;

export type ParityScenario = {
  id: string;
  slug: string;
  canonicalPath: string;
  run: (page: Page) => Promise<void>;
  extract: (page: Page) => Promise<ScenarioSnapshot>;
};

const POKEMON_JSON_FIXTURE = {
  "25": {
    idx: 25,
    slug: { eng: "pikachu" },
    name: { eng: "Pikachu" }
  }
};

const PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAFUlEQVR42mP8z8Dwn4GBgYGJAQoACl8DA2h4JqkAAAAASUVORK5CYII=";

function normalizeText(v: string | null | undefined) {
  return String(v || "").replace(/\r\n/g, "\n").trim();
}

function normalizePokespriteBbcode(v: string) {
  return normalizeText(v).replace(
    /\[url="[^"]*"\]Generated by the PokeSprite Generator\[\/url\]/g,
    "[url=\"<GENERATOR_URL>\"]Generated by the PokeSprite Generator[/url]"
  );
}

function normalizeRainbowDexExtras(v: string) {
  const text = normalizeText(v);
  const duplicatesSection =
    text.match(/=== Duplicates in input \(ignoring gender and level, aggregated by mon\) ===[\s\S]*$/)?.[0] ??
    "=== Duplicates in input (ignoring gender and level, aggregated by mon) ===\n<missing>";

  const markers = [
    text.includes("=== Missing (overall rarity > 10) per variant; up to 20 shown per variant ===")
      ? "missing-section:present"
      : "missing-section:absent",
    text.includes("Goldens are included in the missing list.") ? "goldens-note:present" : "goldens-note:absent",
    text.includes("--- Golden ---") ? "golden-variant:present" : "golden-variant:absent",
    text.includes("--- Shiny ---") ? "shiny-variant:present" : "shiny-variant:absent",
    text.includes("--- Dark ---") ? "dark-variant:present" : "dark-variant:absent",
    text.includes("--- Normal ---") ? "normal-variant:present" : "normal-variant:absent"
  ];

  return [...markers, "", duplicatesSection].join("\n");
}

async function setChecked(page: Page, selector: string, checked: boolean) {
  await page.$eval(
    selector,
    (el, on) => {
      const input = el as HTMLInputElement;
      input.checked = Boolean(on);
      input.dispatchEvent(new Event("input", { bubbles: true }));
      input.dispatchEvent(new Event("change", { bubbles: true }));
    },
    checked
  );
}

export async function installDeterministicNetwork(page: Page) {
  await page.route("https://wiki.tppc.info/**", async (route) => {
    await route.abort();
  });

  await page.route("https://raw.githubusercontent.com/msikma/pokesprite/master/data/pokemon.json", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(POKEMON_JSON_FIXTURE)
    });
  });

  await page.route("https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/pikachu.png", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "image/png",
      body: Buffer.from(PNG_BASE64, "base64")
    });
  });
}

export async function waitForToolRuntime(page: Page) {
  await page.waitForFunction(() => {
    const hasEmbeddedHost = Boolean(document.querySelector(".native-tool-content"));
    const marker = (window as { __TPPC_TOOL_READY?: boolean }).__TPPC_TOOL_READY;
    if (hasEmbeddedHost) return marker === true;
    if (typeof marker === "undefined") return document.readyState === "complete";
    return marker === true;
  });
}

export const PARITY_SCENARIOS: readonly ParityScenario[] = [
  {
    id: "box-organizer-basic",
    slug: "box-organizer",
    canonicalPath: "/tools/box-organizer/",
    async run(page) {
      await page.waitForSelector("#input");
      await page.fill(
        "#input",
        [
          "GoldenAbra\u2642 (Level: 5)",
          "GoldenAbra\u2640 (Level: 3)",
          "DarkEevee\u2640 (Level: 10)",
          "ShinyPikachu\u2642 (Level: 4)",
          "Bulbasaur (Level: 2)"
        ].join("\n")
      );
      await setChecked(page, "#combine", true);
      await page.click("#sortBtn");
      await page.waitForFunction(() => {
        const out = document.querySelector("#output") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.includes("[code]"));
      });
    },
    async extract(page) {
      return {
        output: normalizeText(await page.$eval("#output", (el) => (el as HTMLTextAreaElement).value)),
        status: normalizeText(await page.textContent("#status"))
      };
    }
  },
  {
    id: "perfect-exp-basic",
    slug: "perfect-exp",
    canonicalPath: "/tools/perfect-exp/",
    async run(page) {
      await page.waitForSelector("#current-exp");
      await page.waitForFunction(() => {
        const sel = document.querySelector("#highest-beatable-trainer") as HTMLSelectElement | null;
        return Boolean(sel && sel.options.length > 1);
      });
      await page.fill("#current-exp", "1");
      await page.fill("#desired-exp", "2000");
      await page.uncheck("#use-exp-night");
      await page.click("#submit");
      await page.waitForFunction(() => {
        const rows = document.querySelectorAll("#results-table tbody tr");
        return rows.length > 0;
      });
    },
    async extract(page) {
      return {
        info: normalizeText(await page.textContent("#calculation-info")),
        rows: normalizeText(await page.$eval("#results-table tbody", (el) => (el as HTMLElement).innerText))
      };
    }
  },
  {
    id: "sell-guide-basic",
    slug: "sell-guide",
    canonicalPath: "/tools/sell-guide/",
    async run(page) {
      await page.waitForSelector("#moneyInput");
      await page.fill("#moneyInput", "250");
      await page.fill("#levelInput", "610");
      await page.waitForTimeout(100);
    },
    async extract(page) {
      return {
        levelInput: normalizeText(await page.$eval("#levelInput", (el) => (el as HTMLInputElement).value)),
        marketOut: normalizeText(await page.textContent("#marketOut")),
        buyerOut: normalizeText(await page.textContent("#buyerOut")),
        sellerOut: normalizeText(await page.textContent("#sellerOut")),
        status: normalizeText(await page.textContent("#status"))
      };
    }
  },
  {
    id: "exp-utilities-basic",
    slug: "exp-utilities",
    canonicalPath: "/tools/exp-utilities/",
    async run(page) {
      await page.waitForSelector("#levelInput");
      await page.fill("#levelInput", "100");
      await page.click("#levelToExp .btn.btn-primary.btn-calc");

      await page.fill("#expInput", "1000000");
      await page.click("#expToLevel .btn.btn-primary.btn-calc");

      await page.fill("#levelInput1", "5");
      await page.fill("#levelInput2", "10");
      await page.click("#levelDiff .btn.btn-primary.btn-calc");
    },
    async extract(page) {
      return {
        levelExpOutput: normalizeText(await page.$eval("#levelExpOutput", (el) => (el as HTMLInputElement).value)),
        expLevelOutput: normalizeText(await page.$eval("#expLevelOutput", (el) => (el as HTMLInputElement).value)),
        levelDiffOutput: normalizeText(await page.$eval("#levelDiffOutput", (el) => (el as HTMLInputElement).value))
      };
    }
  },
  {
    id: "pokesprite-generator-basic",
    slug: "pokesprite-generator",
    canonicalPath: "/tools/pokesprite-generator/",
    async run(page) {
      await page.waitForSelector("#pokeInput");
      await page.waitForFunction(() => {
        const status = document.querySelector("#status");
        return Boolean(status && /Loaded/i.test(status.textContent || ""));
      });

      await page.fill("#pokeInput", "Pikachu");
      await page.click("#renderBtn");
      await page.waitForFunction(() => {
        const out = document.querySelector("#bbcodeOut") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        resolved: normalizeText(await page.textContent("#resolved")),
        status: normalizeText(await page.textContent("#status")),
        bbcodeOut: normalizePokespriteBbcode(
          await page.$eval("#bbcodeOut", (el) => (el as HTMLTextAreaElement).value)
        )
      };
    }
  },
  {
    id: "evolution-viewer-basic",
    slug: "evolution-viewer",
    canonicalPath: "/tools/evolution-viewer/",
    async run(page) {
      await page.waitForSelector("#pokeInput");
      await page.waitForFunction(() => {
        const list = document.querySelector("#pokeList") as HTMLDataListElement | null;
        return Boolean(list && list.options.length > 100);
      });
      await page.fill("#pokeInput", "bulbasaur");
      await page.waitForFunction(() => {
        const out = document.querySelector("#jsonOut") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        out: normalizeText(await page.$eval("#out", (el) => (el as HTMLElement).innerText)),
        jsonOut: normalizeText(await page.$eval("#jsonOut", (el) => (el as HTMLTextAreaElement).value))
      };
    }
  },
  {
    id: "ungendered-sorter-basic",
    slug: "ungendered-sorter",
    canonicalPath: "/tools/ungendered-sorter/",
    async run(page) {
      await page.waitForSelector("#inputList");
      await page.fill(
        "#inputList",
        [
          "GoldenMew (?) (Level: 5)",
          "ShinyMew (?) (Level: 6)",
          "DarkMew (?) (Level: 7)",
          "Mew (?) (Level: 8)"
        ].join("\n")
      );
      await page.click("#runButton");
      await page.waitForFunction(() => {
        const out = document.querySelector("#outputText") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        outputText: normalizeText(await page.$eval("#outputText", (el) => (el as HTMLTextAreaElement).value)),
        outputMissing: normalizeText(await page.$eval("#outputMissing", (el) => (el as HTMLTextAreaElement).value)),
        status: normalizeText(await page.textContent("#status"))
      };
    }
  },
  {
    id: "ungendered-families-basic",
    slug: "ungendered-families",
    canonicalPath: "/tools/ungendered-families/",
    async run(page) {
      await page.waitForSelector("#inputList");
      await page.fill(
        "#inputList",
        [
          "GoldenMew (?) (Level: 5)",
          "ShinyMew (?) (Level: 6)",
          "DarkMew (?) (Level: 7)",
          "Mew (?) (Level: 8)"
        ].join("\n")
      );
      await page.click("#runButton");
      await page.waitForFunction(() => {
        const out = document.querySelector("#outputText") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        outputText: normalizeText(await page.$eval("#outputText", (el) => (el as HTMLTextAreaElement).value)),
        outputMissing: normalizeText(await page.$eval("#outputMissing", (el) => (el as HTMLTextAreaElement).value)),
        outputSingles: normalizeText(await page.$eval("#outputSingles", (el) => (el as HTMLTextAreaElement).value)),
        status: normalizeText(await page.textContent("#status"))
      };
    }
  },
  {
    id: "ungendered-diff-basic",
    slug: "ungendered-diff",
    canonicalPath: "/tools/ungendered-diff/",
    async run(page) {
      await page.waitForSelector("#input1");
      await page.fill(
        "#input1",
        [
          "ShinyAbra\u2642 (Level: 5)",
          "ShinyAbra\u2642 (Level: 6)",
          "DarkEevee\u2640 (Level: 10)"
        ].join("\n")
      );
      await page.fill(
        "#input2",
        [
          "DarkEevee\u2640 (Level: 9)",
          "GoldenAbra\u2642 (Level: 1)"
        ].join("\n")
      );
      await page.click("#runButton");
      await page.waitForFunction(() => {
        const out = document.querySelector("#output1") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        output1: normalizeText(await page.$eval("#output1", (el) => (el as HTMLTextAreaElement).value)),
        output2: normalizeText(await page.$eval("#output2", (el) => (el as HTMLTextAreaElement).value)),
        status: normalizeText(await page.textContent("#status"))
      };
    }
  },
  {
    id: "rainbow-dex-basic",
    slug: "rainbow-dex",
    canonicalPath: "/tools/rainbow-dex/",
    async run(page) {
      await page.waitForSelector("#inputList");
      await page.fill(
        "#inputList",
        [
          "GoldenBulbasaur\u2642 (Level: 5)",
          "ShinyBulbasaur\u2640 (Level: 4)",
          "DarkCharmander (Level: 7)",
          "Pikachu\u2642 (Level: 10)"
        ].join("\n")
      );
      await page.click("#runButton");
      await page.waitForFunction(() => {
        const out = document.querySelector("#outputChecklist") as HTMLTextAreaElement | null;
        return Boolean(out && out.value.trim().length > 0);
      });
    },
    async extract(page) {
      return {
        outputChecklist: normalizeText(await page.$eval("#outputChecklist", (el) => (el as HTMLTextAreaElement).value)),
        outputExtras: normalizeRainbowDexExtras(
          await page.$eval("#outputExtras", (el) => (el as HTMLTextAreaElement).value)
        )
      };
    }
  }
] as const;
