import type { PokespriteData, ResolvedPokemon } from "./types";

export const POKEMON_JSON_URL = "https://raw.githubusercontent.com/msikma/pokesprite/master/data/pokemon.json";
export const SPRITE_BASE = "https://raw.githubusercontent.com/msikma/pokesprite/master/pokemon-gen8/regular/";
export const GEN9_BASE = "https://raw.githubusercontent.com/bamq/pokemon-sprites/main/pokemon/regular/";

export function normalizeName(s: string) {
  return String(s || "").trim().toLowerCase();
}

export function resolvePokemonByName(input: string, data: PokespriteData): ResolvedPokemon | null {
  const q = normalizeName(input);
  if (!q) return null;

  for (const [id, entry] of Object.entries(data || {})) {
    const name = String(entry?.name?.eng || "").trim();
    const slug = String(entry?.slug?.eng || "").trim();
    if (!name || !slug) continue;

    if (normalizeName(name) === q || normalizeName(slug) === q) {
      return {
        id,
        name,
        slug,
        generationLabel: "Gen 1-8"
      };
    }
  }

  return null;
}

export function rgbaToHex(r: number, g: number, b: number) {
  const toHex = (n: number) => n.toString(16).padStart(2, "0").toUpperCase();
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

export function imageDataToBbcode(
  rgba: Uint8ClampedArray,
  width: number,
  height: number,
  opts?: { alphaThreshold?: number; xScale?: number }
) {
  const alphaThreshold = Number.isFinite(opts?.alphaThreshold) ? Number(opts?.alphaThreshold) : 30;
  const xScale = Math.max(1, Number.isFinite(opts?.xScale) ? Number(opts?.xScale) : 2);

  const lines: string[] = [];
  const block = "█";

  for (let y = 0; y < height; y += 1) {
    let line = "";
    let x = 0;
    while (x < width) {
      const idx = (y * width + x) * 4;
      const a = rgba[idx + 3];
      if (a < alphaThreshold) {
        line += " ".repeat(xScale);
        x += 1;
        continue;
      }

      const r = rgba[idx];
      const g = rgba[idx + 1];
      const b = rgba[idx + 2];
      const color = rgbaToHex(r, g, b);

      let run = 1;
      while (x + run < width) {
        const nextIdx = (y * width + (x + run)) * 4;
        const na = rgba[nextIdx + 3];
        if (na < alphaThreshold) break;
        const nr = rgba[nextIdx];
        const ng = rgba[nextIdx + 1];
        const nb = rgba[nextIdx + 2];
        if (nr !== r || ng !== g || nb !== b) break;
        run += 1;
      }

      line += `[color=${color}]${block.repeat(run * xScale)}[/color]`;
      x += run;
    }

    lines.push(line.trimEnd());
  }

  return lines;
}

export function buildFootnote(pageUrl: string) {
  return `[size="2"][url="${pageUrl}"]Generated by the PokeSprite Generator[/url][/size]`;
}

export function formatBbcode(lines: string[], pageUrl: string) {
  return `[code]\n${lines.join("\n")}\n[/code]\n\n${buildFootnote(pageUrl)}`;
}
