import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { TOOLS } from "../src/tools/registry";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

async function main() {
  const outFile = path.join(root, "public", "assets", "tools.js");
  await mkdir(path.dirname(outFile), { recursive: true });

  const legacyTools = TOOLS.map((t) => ({
    name: t.name,
    url: `tools/${t.slug}/`,
    desc: t.desc,
    tags: t.tags
  }));

  const contents =
    `// This file is generated by scripts/generate-legacy-tools-js.ts\n` +
    `// Do not edit by hand.\n` +
    `window.TPPC_TOOLS = ${JSON.stringify(legacyTools, null, 2)};\n`;

  await writeFile(outFile, contents, "utf8");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});

